### ISSUE TITLE
Add basiclite x64 version.

### ISSUE THREAD

**Issue by etienned** [bumpx/oracle-instantclient#2]
Is it possible to add the 64bit version of Basic Lite (instantclient-basiclite-linux.x64-12.2.0.1.0.zip)? Currently you only have the 32bit version.

Thank you

**Comment by f3l1x** [comment]
Added  b610f793b0cb4afe4d53557191a2becae6055f1c

**Comment by etienned** [comment]
It was fast. Thanks a lot! It's really appreciated.
