### ISSUE TITLE
Add version 18.5.0.0.0 and 19.3.0.0.0.

### ISSUE THREAD

**Issue by etienned** [bumpx/oracle-instantclient#4]
Do you think you could add the newer versions 18.5.0.0.0 and 19.3.0.0.0?

Thanks

**Comment by f3l1x** [comment]
Hello, could you please download these binaries and create PR? :-)

**Comment by etienned** [comment]
It's no longer necessary! Oracle have changed their download page and we no longer need to login and accept the Licence Agreement. It's now possible to download the client from a direct URL.
